"""Slung-load transport mission.

Fly a quadcopter with a rigid-cable payload from point A to point B.

The cable is modelled as a rigid rod attached to the airframe via a MuJoCo
ball joint.  The pendulum dynamics, ground contact, and constraint forces
are handled entirely by MuJoCo's physics engine.  Perfect sensing is
assumed — payload state is read directly from ``MjData``.
"""

from __future__ import annotations

from enum import Enum

import jax.numpy as jnp
import mujoco
import numpy as np

from uavsim.core.types import (
    HoverGains,
    MultirotorParams,
    PIDGains,
    VehicleState,
)
from uavsim.controllers.trajectory import TrajectoryController
from uavsim.sim.mujoco_sim import MuJoCoSimulator


# ═════════════════════════════════════════════════════════════════════════════
#  Gains tuned for slung-load transport
# ═════════════════════════════════════════════════════════════════════════════

def transport_hover_gains() -> HoverGains:
    """Gentle hover gains that reduce pendulum excitation.

    Compared to default_hover_gains():
      * lower kp_pos  → smoother acceleration
      * higher kd_pos → better velocity damping
      * 20° max tilt  → limits translational jerk
    """
    return HoverGains(
        kp_pos=2.0,
        ki_pos=0.15,
        kd_pos=3.5,
        pos_integral_limit=jnp.array([1.0, 1.0, 0.5]),
        att_gains=PIDGains(
            kp=8.0, ki=0.2, kd=3.0,
            max_output=1.5, integral_limit=0.3,
        ),
        max_tilt=jnp.float32(jnp.deg2rad(20.0)),
        min_alt=0.12,
        min_thrust_ratio=0.3,
    )


# ═════════════════════════════════════════════════════════════════════════════
#  MJCF generation
# ═════════════════════════════════════════════════════════════════════════════

_ATTACH_OFFSET = 0.04  # cable attaches this far below quad centre [m]


def generate_slung_load_mjcf(
    cable_length: float = 0.4,
    payload_mass: float = 0.15,
    payload_radius: float = 0.04,
    cable_radius: float = 0.005,
    cable_mass: float = 0.02,
    cable_damping: float = 0.005,
    point_a: tuple[float, float] = (0.0, 0.0),
    point_b: tuple[float, float] = (3.0, 0.0),
) -> str:
    """Generate MJCF XML for a quadcopter with rigid-cable slung load.

    The model extends the standard quadcopter with:
      * A ball joint at the fuselage bottom connecting a rigid cable body.
      * A payload sphere at the cable tip.
      * Coloured ground markers at the pickup (green) and delivery (red) points.

    Returns an XML string suitable for ``MuJoCoSimulator(vehicle, mjcf_override=...)``.
    """
    ax, ay = point_a
    bx, by = point_b

    # Starting altitude: payload just above ground
    start_alt = _ATTACH_OFFSET + cable_length + payload_radius + 0.02

    # Cable inertia (thin rod about its centre)
    cable_ixx = cable_mass * cable_length ** 2 / 12.0
    cable_izz = cable_mass * cable_radius ** 2 / 2.0
    cable_com_z = -cable_length / 2.0

    # Payload inertia (solid sphere)
    payload_i = 0.4 * payload_mass * payload_radius ** 2

    return f"""\
<?xml version="1.0" ?>
<!--
  Quadcopter + rigid-cable slung load — auto-generated by uavsim.missions.transport
-->
<mujoco model="quadcopter_slung_load">

  <compiler inertiafromgeom="auto"/>
  <option timestep="0.001" gravity="0 0 -9.81" integrator="RK4"/>

  <visual>
    <headlight ambient="0.4 0.4 0.4" diffuse="0.6 0.6 0.6" specular="0.1 0.1 0.1"/>
    <map shadowclip="1" shadowscale="0.6"/>
    <quality shadowsize="2048"/>
    <global offwidth="1280" offheight="720"/>
  </visual>

  <asset>
    <texture name="skybox" type="skybox" builtin="gradient"
             rgb1="0.4 0.6 0.8" rgb2="0.8 0.9 1.0" width="512" height="512"/>
    <texture name="tex_ground" type="2d" builtin="checker"
             rgb1="0.45 0.45 0.45" rgb2="0.55 0.55 0.55" width="512" height="512"/>
    <material name="mat_ground"  texture="tex_ground" texrepeat="8 8"
              specular="0.1" shininess="0.1" reflectance="0.0"/>
    <material name="mat_body"    rgba="0.15 0.20 0.80 1"  specular="0.5" shininess="0.7"/>
    <material name="mat_arm"     rgba="0.20 0.20 0.20 1"  specular="0.2"/>
    <material name="mat_motor"   rgba="0.10 0.10 0.10 1"  specular="0.3"/>
    <material name="mat_rotor"   rgba="0.85 0.15 0.15 0.75" specular="0.2"/>
    <material name="mat_cable"   rgba="0.30 0.30 0.30 1"  specular="0.1"/>
    <material name="mat_payload" rgba="0.90 0.60 0.10 1"  specular="0.4" shininess="0.6"/>
  </asset>

  <worldbody>
    <!-- Ground plane -->
    <geom name="ground" type="plane" size="20 20 0.1" material="mat_ground"/>

    <!-- Pickup marker (green) -->
    <geom name="marker_a" type="cylinder"
          pos="{ax:.4f} {ay:.4f} 0.001" size="0.20 0.002"
          rgba="0.2 0.8 0.2 0.5" contype="0" conaffinity="0"/>

    <!-- Delivery marker (red) -->
    <geom name="marker_b" type="cylinder"
          pos="{bx:.4f} {by:.4f} 0.001" size="0.20 0.002"
          rgba="0.8 0.2 0.2 0.5" contype="0" conaffinity="0"/>

    <!-- ══════════════════════════════════════════════════════════════
         Quadcopter body
         ══════════════════════════════════════════════════════════════ -->
    <body name="body" pos="{ax:.4f} {ay:.4f} {start_alt:.4f}">
      <freejoint name="root"/>

      <!-- Central fuselage -->
      <inertial pos="0 0 0" mass="1.0" diaginertia="0.0082 0.0082 0.0149"/>
      <geom name="body_geom" type="box" size="0.08 0.08 0.04" material="mat_body"/>

      <!-- Arms (decorative) -->
      <geom name="arm_fl_br" type="box" size="0.17 0.015 0.008"
            euler="0 0  0.7854" material="mat_arm" contype="0" conaffinity="0"/>
      <geom name="arm_fr_bl" type="box" size="0.17 0.015 0.008"
            euler="0 0 -0.7854" material="mat_arm" contype="0" conaffinity="0"/>

      <!-- Front-Left motor + rotor -->
      <body name="motor_fl" pos="-0.17 0.17 0.0">
        <inertial pos="0 0 0" mass="0.05" diaginertia="1e-4 1e-4 1e-4"/>
        <geom name="motor_fl_geom" type="cylinder" size="0.016 0.02"
              material="mat_motor" contype="0" conaffinity="0"/>
        <joint name="rotor_fl" type="hinge" axis="0 0 1" limited="false" damping="1e-4"/>
        <geom name="prop_fl" type="cylinder" size="0.115 0.003" pos="0 0 0.022"
              material="mat_rotor" contype="0" conaffinity="0"/>
      </body>

      <!-- Front-Right motor + rotor -->
      <body name="motor_fr" pos="0.17 0.17 0.0">
        <inertial pos="0 0 0" mass="0.05" diaginertia="1e-4 1e-4 1e-4"/>
        <geom name="motor_fr_geom" type="cylinder" size="0.016 0.02"
              material="mat_motor" contype="0" conaffinity="0"/>
        <joint name="rotor_fr" type="hinge" axis="0 0 1" limited="false" damping="1e-4"/>
        <geom name="prop_fr" type="cylinder" size="0.115 0.003" pos="0 0 0.022"
              material="mat_rotor" contype="0" conaffinity="0"/>
      </body>

      <!-- Back-Left motor + rotor -->
      <body name="motor_bl" pos="-0.17 -0.17 0.0">
        <inertial pos="0 0 0" mass="0.05" diaginertia="1e-4 1e-4 1e-4"/>
        <geom name="motor_bl_geom" type="cylinder" size="0.016 0.02"
              material="mat_motor" contype="0" conaffinity="0"/>
        <joint name="rotor_bl" type="hinge" axis="0 0 1" limited="false" damping="1e-4"/>
        <geom name="prop_bl" type="cylinder" size="0.115 0.003" pos="0 0 0.022"
              material="mat_rotor" contype="0" conaffinity="0"/>
      </body>

      <!-- Back-Right motor + rotor -->
      <body name="motor_br" pos="0.17 -0.17 0.0">
        <inertial pos="0 0 0" mass="0.05" diaginertia="1e-4 1e-4 1e-4"/>
        <geom name="motor_br_geom" type="cylinder" size="0.016 0.02"
              material="mat_motor" contype="0" conaffinity="0"/>
        <joint name="rotor_br" type="hinge" axis="0 0 1" limited="false" damping="1e-4"/>
        <geom name="prop_br" type="cylinder" size="0.115 0.003" pos="0 0 0.022"
              material="mat_rotor" contype="0" conaffinity="0"/>
      </body>

      <!-- ════════════════════════════════════════════════════════════
           Slung load: rigid cable + payload
           Ball joint at the fuselage bottom gives 3-DOF pendulum.
           ════════════════════════════════════════════════════════════ -->
      <body name="cable_payload" pos="0 0 -{_ATTACH_OFFSET}">
        <joint name="cable_joint" type="ball" damping="{cable_damping}"/>
        <inertial pos="0 0 {cable_com_z:.6f}" mass="{cable_mass}"
                  diaginertia="{cable_ixx:.6e} {cable_ixx:.6e} {cable_izz:.6e}"/>
        <geom name="cable_geom" type="capsule"
              fromto="0 0 0 0 0 -{cable_length}" size="{cable_radius}"
              material="mat_cable" contype="0" conaffinity="0"/>

        <body name="payload" pos="0 0 -{cable_length}">
          <inertial pos="0 0 0" mass="{payload_mass}"
                    diaginertia="{payload_i:.6e} {payload_i:.6e} {payload_i:.6e}"/>
          <geom name="payload_geom" type="sphere" size="{payload_radius}"
                material="mat_payload"/>
        </body>
      </body>

    </body>
  </worldbody>

  <!-- Exclude quad-body <-> payload contacts (grandchild pair) -->
  <contact>
    <exclude body1="body" body2="payload"/>
  </contact>

  <!-- Actuators drive prop spin visually; thrust is via xfrc_applied -->
  <actuator>
    <motor name="act_fl" joint="rotor_fl" gear="0.01" ctrlrange="-1 1"/>
    <motor name="act_fr" joint="rotor_fr" gear="0.01" ctrlrange="-1 1"/>
    <motor name="act_bl" joint="rotor_bl" gear="0.01" ctrlrange="-1 1"/>
    <motor name="act_br" joint="rotor_br" gear="0.01" ctrlrange="-1 1"/>
  </actuator>

</mujoco>"""


# ═════════════════════════════════════════════════════════════════════════════
#  Mission state machine
# ═════════════════════════════════════════════════════════════════════════════

class MissionPhase(Enum):
    """Phases of a slung-load transport mission."""
    TAKEOFF   = "takeoff"
    TRANSIT   = "transit"
    DESCEND   = "descend"
    STABILIZE = "stabilize"
    DONE      = "done"


class TransportMission:
    """State machine for flying a slung-load payload from A to B.

    Phases
    ------
    TAKEOFF   — ascend to cruise altitude above point A
    TRANSIT   — fly horizontally to point B at cruise altitude
    DESCEND   — lower the quad until the payload nears the ground at B
    STABILIZE — hold position while the payload damps its swing
    DONE      — payload delivered, mission complete

    Parameters
    ----------
    sim : MuJoCoSimulator
        Live simulator instance (used to read payload state).
    point_a, point_b : (2,) array-like
        Pickup and delivery XY coordinates.
    params : MultirotorParams
        Vehicle parameters (should include total system mass).
    cruise_altitude : float
        Cruising altitude during transit [m].
    cable_length : float
        Rigid cable length [m].
    payload_radius : float
        Payload sphere radius [m].
    gains : HoverGains, optional
        Controller gains.  Defaults to *transport_hover_gains()*.
    """

    def __init__(
        self,
        sim: MuJoCoSimulator,
        point_a: tuple[float, float],
        point_b: tuple[float, float],
        params: MultirotorParams,
        cruise_altitude: float = 1.5,
        cable_length: float = 0.4,
        payload_radius: float = 0.04,
        gains: HoverGains | None = None,
    ):
        self.sim = sim
        self.point_a = np.asarray(point_a, dtype=float)
        self.point_b = np.asarray(point_b, dtype=float)
        self.cruise_alt = cruise_altitude
        self.cable_length = cable_length
        self.payload_radius = payload_radius

        # Resolve MuJoCo body ID for payload
        self._payload_id = mujoco.mj_name2id(
            sim.model, mujoco.mjtObj.mjOBJ_BODY, "payload")

        # Placement altitude: quad height when payload rests on ground
        self._place_alt = (
            _ATTACH_OFFSET + cable_length + payload_radius
        )

        # Controller
        gains = gains or transport_hover_gains()
        self.controller = TrajectoryController(
            params, gains=gains, acceptance_radius=0.20)

        # State
        self.phase = MissionPhase.TAKEOFF
        self._stabilize_start: float = 0.0

        # Statistics
        self.max_swing_deg: float = 0.0
        self.transit_start_time: float = 0.0
        self.transit_end_time: float = 0.0
        self.payload_history: list[np.ndarray] = []

        # Kick off takeoff
        self._enter_phase(MissionPhase.TAKEOFF)

    # ── payload sensing (perfect) ────────────────────────────────────────

    @property
    def payload_position(self) -> np.ndarray:
        """World-frame position of the payload centre."""
        return self.sim.data.xpos[self._payload_id].copy()

    @property
    def swing_angle_deg(self) -> float:
        """Cable swing angle from vertical [deg]."""
        quad_pos = np.asarray(self.sim.get_state().position)
        pay_pos = self.payload_position
        # Vector from attachment point to payload
        attach = quad_pos.copy()
        attach[2] -= _ATTACH_OFFSET
        cable_vec = pay_pos - attach
        # Angle from straight-down vertical
        cos_a = -cable_vec[2] / (np.linalg.norm(cable_vec) + 1e-8)
        return float(np.degrees(np.arccos(np.clip(cos_a, -1.0, 1.0))))

    # ── phase management ─────────────────────────────────────────────────

    def _enter_phase(self, phase: MissionPhase) -> None:
        self.phase = phase
        if phase == MissionPhase.TAKEOFF:
            wp = [self.point_a[0], self.point_a[1], self.cruise_alt]
            self.controller.set_waypoints([wp])

        elif phase == MissionPhase.TRANSIT:
            wp = [self.point_b[0], self.point_b[1], self.cruise_alt]
            self.controller.set_waypoints([wp])

        elif phase == MissionPhase.DESCEND:
            wp = [self.point_b[0], self.point_b[1], self._place_alt]
            self.controller.set_waypoints([wp])

        elif phase == MissionPhase.STABILIZE:
            wp = [self.point_b[0], self.point_b[1], self._place_alt]
            self.controller.set_waypoints([wp])

        elif phase == MissionPhase.DONE:
            # Hold current position
            wp = [self.point_b[0], self.point_b[1], self._place_alt]
            self.controller.set_waypoints([wp])

    # ── main update ──────────────────────────────────────────────────────

    def update(self, state: VehicleState, dt: float) -> jnp.ndarray:
        """Compute motor commands and handle phase transitions.

        Returns (4,) throttle [0, 1].
        """
        pos = np.asarray(state.position)
        pay_pos = self.payload_position
        self.payload_history.append(pay_pos.copy())

        # Track swing
        swing = self.swing_angle_deg
        self.max_swing_deg = max(self.max_swing_deg, swing)

        # ── phase transitions ────────────────────────────────────────
        if self.phase == MissionPhase.TAKEOFF:
            alt_ok = pos[2] > self.cruise_alt - 0.15
            xy_ok = np.linalg.norm(pos[:2] - self.point_a) < 0.3
            vel_ok = abs(float(state.velocity[2])) < 0.3
            if alt_ok and xy_ok and vel_ok:
                self.transit_start_time = state.time
                self._enter_phase(MissionPhase.TRANSIT)

        elif self.phase == MissionPhase.TRANSIT:
            xy_ok = np.linalg.norm(pos[:2] - self.point_b) < 0.3
            alt_ok = abs(pos[2] - self.cruise_alt) < 0.2
            if xy_ok and alt_ok:
                self.transit_end_time = state.time
                self._enter_phase(MissionPhase.DESCEND)

        elif self.phase == MissionPhase.DESCEND:
            alt_ok = abs(pos[2] - self._place_alt) < 0.1
            if alt_ok:
                self._stabilize_start = state.time
                self._enter_phase(MissionPhase.STABILIZE)

        elif self.phase == MissionPhase.STABILIZE:
            pay_xy_err = np.linalg.norm(pay_pos[:2] - self.point_b)
            near = pay_xy_err < 0.15
            settled = swing < 2.0  # swing < 2°
            timeout = (state.time - self._stabilize_start) > 5.0
            if (near and settled) or timeout:
                self._enter_phase(MissionPhase.DONE)

        return self.controller.update(state, dt)

    # ── queries ──────────────────────────────────────────────────────────

    @property
    def done(self) -> bool:
        return self.phase == MissionPhase.DONE

    @property
    def placement_error(self) -> float:
        """Horizontal distance from payload to delivery point [m]."""
        pay = self.payload_position
        return float(np.linalg.norm(pay[:2] - self.point_b))
